name: 'Build PDF slides'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Install AgioUnicode font
        run: mkdir -p ~/.local/share/fonts && cp AgioUnicode.ttf ~/.local/share/fonts

      - name: Cache Tectonic data
        uses: actions/cache@v3
        with:
          path: ~/.cache/Tectonic
          key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
          restore-keys: |
            ${{ runner.os }}-tectonic-

      - name: Set up Tectonic + Biber
        uses: wtfjoke/setup-tectonic@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tectonic-version: '0.12.0'
          biber-version: '2.16'

      - name: Run Tectonic + Biber
        run: tectonic -X build

      - name: Upload PDF slides
        uses: actions/upload-artifact@v3
        with:
          name: Slides
          path: build.pdf
